name: Build Falco Plugin (.so)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-linux-so:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install build-essential
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build plugin (.so)
        run: |
          go build -buildmode=c-shared -o libjson.so ./plugin

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: libjson.so
          path: libjson.so